"""Jester (~2:20, 100 bars @174) - drill'n'bass mischief, Aphex/Squarepusher school:
an innocent music box keeps trying to play its tune while a possessed Amen
tears itself apart around it. Chop patterns are generated by seeded random.

  b0-7    the music box, alone and innocent
  b8-15   the break walks in politely... and starts twitching
  b16-31  mangle I: generative chops, pitch-warped slices, acid jabs
  b32-39  sudden calm: the box plays on over halftime, as if nothing happened
  b40-59  mangle II: full drill - 32nd rolls, scrambled slices, hoover screams
  b60-63  fake ending (don't trust it)
  b64-87  the reward: the groove finally locks, tune and chaos in harmony
  b88-99  wind-down: the box runs out of spring, slowing, sagging, one last tick
"""
import numpy as np
from amenlib import *

rng = np.random.default_rng(303)
np.random.seed(303)
s = Session(100, tail=2.5)

# music box tune, 2 bars (C major, childlike), (step, midi)
BOX = [(0, 84), (2, 88), (4, 91), (6, 88), (8, 93), (10, 91), (12, 88), (14, 84),
       (16, 86), (18, 89), (20, 93), (22, 89), (24, 96), (26, 93), (28, 91), (30, 86)]

def musicbox(b0, gain=0.13, detune=1.0):
    for st, note in BOX:
        seg = bell(midi(note) * detune, 2.5)
        s.place(s.pos(b0) + int(st * STEP), reverb(panned(seg, np.sin(st) * 0.5),
                                                   decay=2.5, wet=0.4), gain)

def stutter(t, seg, times, gap_steps, gain=1.0, ramp=0.85):
    for i in range(times):
        s.place(t + int(i * gap_steps * STEP), seg, gain * ramp ** i)

ONSETS = [(0, 0), (0, 2), (0, 4), (0, 10), (0, 12), (3, 2), (3, 10), (2, 12)]

def mangle_bar(b, intensity=1.0):
    """generative drill chopping: the count is sacred - kick on 1, snares on
    2 and 4, always, at full volume; chaos lives between the anchors, quieter"""
    s.place(s.pos(b, 0), K)
    s.place(s.pos(b, 4), SN)
    s.place(s.pos(b, 12), S2)
    if rng.random() < 0.5:
        s.place(s.pos(b, 10), K2, 0.8)
    st = 1.0
    while st < 16:
        if st in (4.0, 12.0):                              # don't bury the backbeat
            st += 1.0
            continue
        r = rng.random()
        sb, ss = ONSETS[rng.integers(len(ONSETS))]
        ln = float(rng.choice([0.5, 1.0, 1.0, 2.0]))
        seg = get(sb, ss, max(ln, 1))
        if r < 0.18 * intensity:                           # pitch-warp
            seg = pitched(seg, float(rng.choice([0.5, 0.75, 1.5, 2.0])))
        elif r < 0.30 * intensity:
            seg = rev(seg)
        elif r < 0.42 * intensity:
            seg = bitcrush(seg, bits=5, downsample=int(rng.choice([3, 5, 8])))
        elif r < 0.50:                                     # 32nd stutter burst
            stutter(s.pos(b, st), get(sb, ss, 1)[:int(0.5 * STEP)],
                    int(rng.integers(3, 7)), 0.5, 0.6)
            st += 2.0
            continue
        elif r < 0.58:                                     # rest: silence is rhythm too
            st += ln
            continue
        s.place(s.pos(b, st), seg, float(rng.uniform(0.45, 0.7)))
        st += ln

def acid_jabs(b, root=45):
    for st in (3.5, 7, 11.5, 14):
        if rng.random() < 0.6:
            note = root + int(rng.choice([0, 0, 12, 3, -2]))
            s.place(s.pos(b, st), acid(midi(note), 1.5, cutoff=int(rng.integers(500, 1400)),
                                       accent=rng.random() < 0.4), 0.20)

def bass_hits(b, root=45):
    s.place(s.pos(b, 0), sub(midi(root - 12), 3), 0.30)
    if rng.random() < 0.5:
        s.place(s.pos(b, 10), sub(midi(root - 12) * float(rng.choice([1, 1.5, 2])), 2), 0.22)

# ================= the music box (b0-7) =================
for b in (0, 2, 4, 6):
    musicbox(b)
s.place(s.pos(0), crackle(128), 0.4)
s.place(s.pos(6, 14), zap(1.5), 0.1)                       # something stirs...

# ================= polite entrance, twitching (b8-15) =================
for b in range(8, 16):
    if b in (11, 14):
        mangle_bar(b, 0.7)
    else:
        s.place(s.pos(b), bar_of([0, 1, 0, 2][b % 4]), 0.9)
        if rng.random() < 0.5:                             # nervous tics
            stutter(s.pos(b, float(rng.choice([7, 15]))), SN1[:int(0.5 * STEP)], 4, 0.5, 0.8)
    bass_hits(b)
for b in (8, 12):
    musicbox(b, 0.11)
s.place(s.pos(8), CR, 0.7)

# ================= mangle I (b16-31) =================
s.place(s.pos(16), subdrop(8), 0.45)
s.place(s.pos(16), CR, 0.9)
for b in range(16, 32):
    mangle_bar(b, 0.9)
    acid_jabs(b)
    bass_hits(b)
for b in (20, 26):                                         # box fights through
    musicbox(b, 0.10, detune=float(rng.choice([1.0, 1.0, 0.996])))
s.place_echo(s.pos(24, 14), zap(2), 0.14, times=2, delay_steps=2, fb=0.45)
s.pat(31, [(8, SN1, 0.6), (10, SN1, 0.7), (12, SN1, 0.85), (13, SN1, 0.9),
           (14, SN1), (15, SN1)])

# ================= sudden calm (b32-39) =================
for b in range(32, 40):
    s.pat(b, [(0, K, 0.85), (8, SN, 0.85), (14, K2, 0.6)])
    s.place(s.pos(b, 0), sub(midi(33), 6), 0.24)
for b in (32, 34, 36, 38):
    musicbox(b, 0.14)
s.place(s.pos(32), pad([midi(n) for n in (57, 64, 72, 76)], 64, 1200), 0.10)
s.place(s.pos(38), riser(32), 0.55)
s.pat(39, [(12, SN1, 0.7), (13, SN1, 0.8), (14, SN1, 0.9), (15, SN1)])

# ================= mangle II: full drill (b40-59) =================
s.place(s.pos(40), subdrop(10, 80, 27), 0.5)
s.place(s.pos(40), CR, 0.95)
for b in range(40, 60):
    mangle_bar(b, 1.0)
    acid_jabs(b)
    bass_hits(b)
    if b % 4 == 2:                                         # hoover screams
        s.place(s.pos(b, float(rng.choice([2, 6, 10]))),
                hoover(midi(int(rng.choice([45, 48, 52]))), 2), 0.24)
for b in (44, 52):
    musicbox(b, 0.09, detune=0.993)                        # the box is hurting now
s.place(s.pos(48), bitcrush(bar_of(3), 4, 6), 0.9)         # one fully crushed bar
for st in np.arange(8, 16, 0.5):                           # 32nd death-roll
    s.place(s.pos(59, st), SN1, 0.5 + (st - 8) * 0.06)

# ================= fake ending (b60-63) =================
s.place(s.pos(60), crackle(48), 0.4)
musicbox(60, 0.10)
s.place(s.pos(62, 8), zap(1.5, 3000, 50), 0.12)
stutter(s.pos(63, 12), K[:int(0.5 * STEP)], 6, 0.5, 1.0, ramp=1.1)   # ...psych!

# ================= the reward (b64-87) =================
s.place(s.pos(64), subdrop(10), 0.5)
s.place(s.pos(64), CR, 0.9)
for b in range(64, 88):
    if b % 8 == 7:
        mangle_bar(b, 0.8)
    else:
        s.place(s.pos(b), bar_of([0, 1, 2, 1][b % 4]), 0.92)
    s.place(s.pos(b, 0), wobble(midi(33), 14, 2.2 if b % 2 == 0 else 3.3), 0.34)
for b in range(64, 88, 2):
    musicbox(b, 0.12)                                      # tune and chaos, in harmony
for b in range(72, 88, 8):
    s.place(s.pos(b), pad([midi(n) for n in (57, 64, 72, 76)], 128, 1500), 0.08)
s.place(s.pos(80), CR, 0.6)
s.pat(87, [(8, SN1, 0.6), (10, SN1, 0.75), (12, SN1, 0.85), (14, SN1), (15, rev(SN1), 0.8)])

# ================= wind-down (b88-99) =================
for b in range(88, 92):
    s.pat(b, [(0, K, 0.8), (8, SN, 0.75)])
    s.place(s.pos(b, 0), sub(midi(33), 6), 0.2)
musicbox(88, 0.12)
s.place(s.pos(90), crackle(80), 0.45)
t0 = s.pos(92); gap = 2.0                                  # the spring runs out
for i, (st, note) in enumerate(BOX[:12]):
    f = 1 - i * 0.022                                      # each tick lower, later
    seg = reverb(pitched(bell(midi(note), 2.5), f), decay=3.5, wet=0.5)
    s.place(t0 + int((st * gap ** (i / 8)) * STEP), seg, 0.12 * (1 - i * 0.055))
s.place(s.pos(97), reverb(pitched(bell(midi(72), 3), 0.9), decay=6.0, wet=0.8), 0.10)
s.place(s.pos(98, 4), K, 0.4)                              # one last tick
s.place(s.pos(98, 4), sub(midi(21), 12), 0.15)

s.render('amen_jester_174.wav', drive=1.3)
